language: node_js
node_js:
  - 12

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=sbonnick/yasetl
    - CC_TEST_REPORTER_ID=84bc58b9d8136c9d527a40c0acac52b53064cdfbdab2cd3aefecf7b279795c0f

jobs:
  include:
  
    - stage: Test
      install: 
        - npm install
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: 
        - npm test
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - stage: Deploy Docker Container
      script:
        - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
        - docker build -t $REPO:$TAG . 
      after_success:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
            docker tag $REPO:$COMMIT $REPO:$TAG;
            docker login -u $DOCKER_USER -p $DOCKER_PASS;
            docker tag $REPO:$COMMIT $REPO:$TRAVIS_BUILD_NUMBER;
            docker push $REPO;
          fi